title: "Trabajo de Economía - Fabián Báez"
description: "Proyecto académico sobre economía, tecnología y redes."
theme: jekyll-theme-cayman
title: Tu título aquí
description: Tu descripción aquí
include:
  - assets/css/custom.css

